trigger:
  - main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

stages:
  # Continuous Integration (CI)
  - stage: Build
    jobs:
      - job: BuildAndTest
        displayName: 'Build and Test Job'
        steps:
          # Checkout code from GitHub
          - task: Checkout@1

          # # Prepare SonarCloud analysis
          # - task: SonarCloudPrepare@1
          #   inputs:
          #     SonarCloud: 'SonarCloudServiceConnection'  # Service connection name
          #     organization: 'devopsgroupassignment'            # SonarCloud organization key
          #     projectKey: 'COMP308_GroupProject'      # SonarCloud project key
          #     projectName: 'DevopsGroupAssignment/COMP308_GroupProject'

          # Use Maven for Java projects
          - script: |
              mvn clean install
            displayName: 'Compile the project'

          # Run unit tests
          - script: |
              mvn test
            displayName: 'Run unit tests'

          # Publish test results
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/TEST-*.xml'

          # Run SonarCloud analysis
          - task: SonarCloudAnalyze@1

          # Publish SonarCloud quality gate results
          - task: SonarCloudPublish@1
