trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndTest
    displayName: 'Build and Test Application'
    jobs:
      - job: BuildAndTestJob
        displayName: 'Build and Test Job'
        steps:
          # Checkout code from GitHub
          - checkout: self

          # Install Node.js Manually
          - script: |
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
              node -v
              npm -v
            displayName: 'Install Node.js'

          # Install Dependencies
          - script: |
              npm install
            displayName: 'Install Dependencies'

          # Build the React application
          - script: |
              npm run build
            displayName: 'Build React Application'

          # Run Tests
          - script: |
              npm test -- --coverage
            displayName: 'Run Unit Tests'
